language: python

python:
  - "2.7"

env:
    - CINCH_GITHUB_CLIENT_ID='' CINCH_GITHUB_CLIENT_SECRET='' CINCH_GITHUB_CALLBACK_URL='' CINCH_NAMEKO_AMQP_URI='amqp://guest:guest@localhost//cinch' CINCH_SERVER_NAME='ci-dashboard.example.com'

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - make test
